# Generated by Django 4.2.4 on 2023-09-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="products", new_name="product",),
    ]
