# Generated by Django 4.2.5 on 2023-09-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.CharField(default="NA", max_length=20),
        ),
    ]
