# Generated by Django 4.2.5 on 2023-09-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
