# Generated by Django 4.2.5 on 2023-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
